### ISSUE TITLE
Create PrimaryUser fails

### ISSUE THREAD

**Issue by jesseransom** [FocusVision/ember-admin#7]
In combination with frontend-unified-login, we have an error when we click Create to add a PrimaryUser to a company.

To reproduce;
* Click companies
* Click a company from the list
* Click PrimaryUser
* Click Create
![createprimaryuser](https://user-images.githubusercontent.com/10145510/27201895-3a20ba9a-51d4-11e7-9305-de78d7524798.png)
![createprimaryuser_console](https://user-images.githubusercontent.com/10145510/27201896-3a250f50-51d4-11e7-916b-167dc3d8ed2d.png)

**Comment by rsullivan00** [comment]
This is resolved by https://github.com/FocusVision/ember-admin/pull/14
