### ISSUE TITLE
Need to be able to set some associations by selection rather than entry

### ISSUE THREAD

**Issue by jesseransom** [FocusVision/ember-admin#9]
Currently we can only create assocations between two types of items by selecting one and creating a new instance of the other.

E.g. Select a company, select the Users association, create a new User.

In the above instance, we need to be able to Select a company, select the Users association, and then select from existing users a user to associate with the current company.

This is a specific example; we need to be able to create associations in this manner for all suitable types, not only the Company/User relationship.

**Comment by rsullivan00** [comment]
This is complete
